hamcrest/JavaHamcrest

hamcrest-library/src/main/java/org/hamcrest/text/IsEqualIgnoringCase.java
hamcrest-library/src/main/java/org/hamcrest/text/IsEqualIgnoringWhiteSpace.java
hamcrest-library/src/test/java/org/hamcrest/text/IsEqualIgnoringCaseTest.java
hamcrest-library/src/test/java/org/hamcrest/text/IsEqualIgnoringWhiteSpaceTest.java

'equalToIgnoringCase("heLLo")' -> 'a string equal to "heLLo" ignoring case'
'equalToIgnoringWhiteSpace("hello")' -> 'a string equal to "hello" ignoring white space'

IsEqualIgnoringCase, IsEqualIgnoringWhiteSpace: description in plain English

---

build.gradle

With this change:
```
$ ./gradlew test
[..]
org.hamcrest.core.AllOfTest > failingTest FAILED
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.fail(Assert.java:95)
at org.hamcrest.core.AllOfTest.failingTest(AllOfTest.java:72)
409 tests completed, 1 failed
:test FAILED
[..]
```
Before this change:
```
$ ./gradlew test
[..]
org.hamcrest.core.AllOfTest > failingTest FAILED
java.lang.AssertionError at AllOfTest.java:72
409 tests completed, 1 failed
:test FAILED
[..]
```

gradle should output the stacktrace for test failures

---

hamcrest-library/src/main/java/org/hamcrest/Matchers.java
hamcrest-library/src/main/java/org/hamcrest/collection/IsMapEntry.java
hamcrest-library/src/main/java/org/hamcrest/collection/IsMapWithEntries.java
hamcrest-library/src/test/java/org/hamcrest/collection/IsMapEntryTest.java
hamcrest-library/src/test/java/org/hamcrest/collection/IsMapWithEntriesTest.java

This adds two complementary matchers for working with maps.
The main matcher is `IsMapWithEntries`, which is just a `FeatureMatcher` for Map::entrySet. This is essentially an escape hatch from the world of maps to the world of true collections; it allows a user to write matches on maps in terms of their set of entries, using the rich set of matchers available for collections (principally `contains` and friends).
The second matcher is `IsMapEntry`, which makes it easy to write matches on the map entries themselves.
I end up writing these two matchers, in some form, in most projects i work on, because this approach so useful. Specifically, i think it's much more useful to be able to view maps as collections than it is to have a range of matchers specifically for maps.
It's possible i'm …

Map entry matchers

---

hamcrest-library/src/main/java/org/hamcrest/text/StringContainsInOrder.java
hamcrest-library/src/test/java/org/hamcrest/text/StringContainsInOrderTest.java

Eg: StringContainsInOrder(asList("abc", "abc")) should fail when matching "---abc---"
For now matchesSafely does not increment 'fromIndex', the next call to indexOf does not return -1; so it does not fail.

Fix StringContainsInOrder to detect if a repeated pattern is missing

---

build.gradle

This fixes #11. The plugin automatically determines Import-Package and
Export-Package based on analysis of the classes, and also adds
Tool, Bundle-Name, Bundle-Version, Bundle-SymbolicName and
others.
The manifest after this change looks like:
Manifest-Version: 1.0
Export-Package: org.hamcrest;version="2.0.0.0";uses:="javax.xml.namesp
ace,org.hamcrest.collection,org.hamcrest.core,org.hamcrest.internal,o
rg.w3c.dom",org.hamcrest.beans;version="2.0.0.0";uses:="org.hamcrest"
,org.hamcrest.collection;version="2.0.0.0";uses:="org.hamcrest",org.h
amcrest.comparator;version="2.0.0.0";uses:="org.hamcrest",org.hamcres
t.core;version="2.0.0.0";uses:="org.hamcrest",org.hamcrest.internal;v
ersion="2.0.0.0";uses:="org.hamcrest",org.hamcrest.io;version="2.0.0. …

Apply the 'osgi' plugin, so the jar includes a bundle manifest.

---

hamcrest-library/src/test/java/org/hamcrest/io/FileMatchersTest.java

java.nio.file methods avoid loosing errornous states because of boolean
return values which need to be checked whereas IOException thrown by
java.nio.file methods are enforced by the compiler.

Change java.io.File to java.nio.file methods

---

build.gradle

added maven-publish plugin to build.gradle in order to be able to run `./gradlew publishToMavenLocal` and speed up usage of local fixes

added maven-publish plugin to build.gradle

---

.travis.yml

Caching build dependencies on a CI system can hide the unavailability
of dependencies for download. The CI build is of higher quality if it
tests the availability of all build dependencies. The increase in
data volume to transfer and the build time is minimal.

Remove caching of gradle dependencies

---

hamcrest-core/src/main/java/org/hamcrest/core/StringContains.java
hamcrest-core/src/main/java/org/hamcrest/core/StringEndsWith.java
hamcrest-core/src/main/java/org/hamcrest/core/StringRegularExpression.java
hamcrest-core/src/main/java/org/hamcrest/core/StringStartsWith.java

Fixing a copy/pasted java-doc + making java-doc in `StringRegularExpression` more consistent with other matchers.

Clean-up java-doc of String-related matchers

---

docs/index.html

I've replace links to two outdated pages on the old Google Code site. The replacement pages are currently on the JavaHamcrest wiki on GitHub.
For the tutorial, I've linked to the existing Tutorial on the wiki. It's still out of date, but I plan to refresh it soon.
For the distributables, I've created a new wiki page. I'd appreciate it if people could review the page for accuracy and improvements.

Update links to Tutorial and Distributables

---

.gitignore
build.gradle
hamcrest-core/hamcrest-core.gradle
hamcrest-library/hamcrest-library.gradle
settings.gradle

This is done by converting to a multi-project gradle build, with subprojects for `hamcrest-core` and `hamcrest-library`. The root project is responsible for combining all the individual jars into `hamcrest-all.jar`, as well as configuring the publishing.
Note that this changes the version from '2.0.0.0' to '1.4-SNAPSHOT'

 Build separate jars for core, library, and all.

---

build.gradle

Change license name from "BSD Licence 3" to "BSD License 3". This typo
fails automated license checks in a project that has
hamcrest dependency.

Fix typo in license name

---

hamcrest/src/main/java/org/hamcrest/core/AllOf.java
hamcrest/src/main/java/org/hamcrest/core/AnyOf.java
hamcrest/src/test/java/org/hamcrest/core/AllOfTest.java
hamcrest/src/test/java/org/hamcrest/core/AnyOfTest.java

Add a way to construct the `AllOf`, `AnyOf` matchers using the `varargs`.
Some projects prohibit the using of static imports/methods, therefore we have to wrap the matchers to the `Iterable`, it's not convenient and looks a bit ugly.
@tumbarumba , could you please review/give feedback on this pull request?

AllOf/AnyOf: Pass the matchers to constructor using varargs

---

gradle/wrapper/gradle-wrapper.properties
settings.gradle

Gradle 5.2 is not compatible with Java 1.7
This reverts commit 3626acd09e5db54de318680c1fa19bf5d9f211bd.

Revert "Upgrade Gradle 4.10.2 -> 5.2"

---

hamcrest/src/main/java/org/hamcrest/Matchers.java

Use "<? super T>" for all arguments of anyOf

---

docs/tutorial.md

The Java "or" operator (`||`) disappears in the tutorial because the pipe characters must be escaped because of Kramdown bug.

Documentation: Escape pipe characters in tutorial

---

.travis.yml

Need to select an older Ubuntu distribution that supports JDK7

Downgrade Travis environment to Trusty

---

hamcrest/src/main/java/org/hamcrest/MatcherAssert.java
hamcrest/src/test/java/org/hamcrest/MatcherAssertTest.java

I noticed that when I log an assertion error created by Hamcrest that it uses a single line feed character (Unix style end-of-line). Since the rest of my log uses carriage return / line feed pairs (Windows style end-of-line) this will confuse some editors like Vim or Eclipse which generally expect a file to use the same style throughout.
Rather than hardcoding one or the other, the `System.lineSeparator()` function will return the end of line separator appropriate for the current runtime, i.e. "\r\n" on Windows and "\n" on Unix. This way it will adapt to the Java runtime's platform. And should for some reason a user prefer the other style, they should be able to set the `line.separator` property at startup.

Use platform-specific line separators

---

build.gradle
checkstyle.xml
hamcrest/src/main/java/org/hamcrest/collection/IsCollectionWithSize.java
hamcrest/src/main/java/org/hamcrest/collection/IsIterableContainingInOrder.java
hamcrest/src/test/java/org/hamcrest/collection/IsIterableContainingInOrderTest.java
hamcrest/src/test/java/org/hamcrest/object/HasToStringTest.java
hamcrest/src/test/java/org/hamcrest/text/IsEqualIgnoringCaseTest.java

As suggested in #214 the checkstyle setup can be put forward step by
step in order to minimize controversy. The start contains a rule to
enforce spaces instead of tab characters which are already used in
roughly 99.99% of the source.

Start checkstyle setup 2

---

docs/distributables.md

The catches a version in the docs that got missed in faf09f4f25b4282e75ca423e7f593d9cbaa1ca96

Update the maven dependency to 2.2 as well.

---

.travis.yml

- Adds explicit `os` definition: Github now can build using macos and windows so it is a good practice include the `os` definition on `yml`.
- Re-order commands to follow Travis order of execution.
- Adds new java versions `openjdk11` and `openjdk14`

Update Travis CI syntax

---

hamcrest/src/main/java/org/hamcrest/io/FileMatchers.java
hamcrest/src/test/java/org/hamcrest/io/FileMatchersTest.java

e.g.
```text
Expected: an existing File
but: 'filename.txt' is not a file
```

Show filename when file matchers fail

---

hamcrest/src/main/java/org/hamcrest/Matchers.java

`hasLength(Matcher)` signature already exists, but currently client code must import `CharSequenceLength` directly in order to use it, unlike `hasLength(int)` which is already present.
This PR exposes it in the main Matchers object, similarly to how `hasSize(Matcher)` and `hasSize(int)`  are both present.

expose hasLength(Matcher) in Matchers

---

docs/tutorial.md

Changed
- "invaluble" to "invaluable"
- removed comma
- "overspecifying" to "over specifying"
- formatting added to `is` and `is(T value)`

Fixed typos in tutorial and added formatting for readability

---

.github/workflows/ci.yaml

Prep for next java non-LTS whilst still early access.

GitHub Actions add java-18-ea

---

hamcrest/src/main/java/org/hamcrest/collection/IsUnmodifiableCollection.java
hamcrest/src/test/java/org/hamcrest/collection/IsUnmodifiableCollectionTest.java

My proposal of implementation of the issue #249 .
Should work fine for both `Collections::unmodifiable*` implementations, and guava `Immutable*` collections.

IsUnmodifiableCollection matcher feature #249

---

hamcrest/src/main/java/org/hamcrest/SelfDescribing.java

I stumbled upon this small typo while browsing the code. 😄

Fix a typo in the javadoc of SelfDescribing

---

docs/_includes/head.html
docs/_layouts/default.html

Docs are currently pointing to an old image url that doesn't exist

Fix 'Fork me on GitHub' banner

---

docs/javadoc/index.html

Docs are currently pointing to an old image url that doesn't exist

Fix 'Fork me on GitHub' banner in docs

---

CHANGES.md
build.gradle

Include the LICENSE file inside the jars

---

hamcrest/src/main/java/org/hamcrest/Matchers.java
hamcrest/src/main/java/org/hamcrest/optional/OptionalEmpty.java
hamcrest/src/main/java/org/hamcrest/optional/OptionalWithValue.java
hamcrest/src/test/java/org/hamcrest/optional/OptionalMatchersTest.java

This change was waiting for releasing 3.0 with JDK 8 compatibility.
Matchers for `java.util.Optional`:
* `OptionalMatchers.emptyOptional()`
* `OptionalMatchers.optionalWithValue()`
* `OptionalMatchers.optionalWithValue(value)`
* `OptionalMatchers.optionalWithValue(Matcher)`

java.util.Optional matchers

---

CHANGES.md
hamcrest/src/main/java/org/hamcrest/CoreMatchers.java
hamcrest/src/main/java/org/hamcrest/Matchers.java
hamcrest/src/main/java/org/hamcrest/collection/HasItemInArray.java
hamcrest/src/main/java/org/hamcrest/collection/IsIterableContainingInAnyOrder.java
hamcrest/src/main/java/org/hamcrest/core/IsCollectionContaining.java
hamcrest/src/main/java/org/hamcrest/core/IsIterableContaining.java
hamcrest/src/test/java/org/hamcrest/collection/IsMapContainingTest.java
hamcrest/src/test/java/org/hamcrest/core/IsCollectionContainingTest.java
hamcrest/src/test/java/org/hamcrest/core/IsIterableContainingTest.java

As discussed in #252, there are problems with matching against polymorphic collections.
This fix attempts to apply the PECS rule (producer extends, consumer super) to the Hamcrest IsIterableContaining matcher. In this instance, a collection of items should be treated as a producer according to this rule, while a matcher acts as a consumer. There was some confustion about PECS in the context of collections of matchers, but I'm hoping this change addresses those issues.
I'm keen for others to test this work out

Allow matching against polymorphic collections

---

CHANGES.md
hamcrest/src/main/java/org/hamcrest/CoreMatchers.java
hamcrest/src/main/java/org/hamcrest/MatcherAssert.java
hamcrest/src/main/java/org/hamcrest/Matchers.java

CoreMatchers, MatcherAssert, and Matchers had private contructors added to fix javadoc warnings. Unfortunately, this can break existig users of the classes.
Fixes #427

Restore public constructors for compatibility
